### ISSUE TITLE
[Enhancement]: Support stats-log and delta-log in SaveBinlogPaths

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#10078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Support stats-log and delta-log in SaveBinlogPaths

### Why is this needed?

As Delete MEP designed, datacoord shall save currently so-called stats-log and delta-log via SaveBinlogPaths API.
According to Compaction MEP, extra delta log info is needed to determine whether a segment shall be compacted.

### Anything else?

See also #9927

### Task List

- [x] Update SaveBinlogPaths proto #10080
- [x] Update Datacoord SaveBinlogPaths logic #10156 
- [x] Add more info about delta log in datanode #10159
