### ISSUE TITLE
[Bug]: MqttMsgStream `AsConsumer` blocks if seek position is the last msg in it

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#11098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version:a0a3a88
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

MqttMsgStream `AsConsumer` blocks if seek position is the last msg in it.
Which causes the datanode stucks and holds the lock and unable to provide service 

### Expected Behavior

Data Node continue to provide services even seek position is the last msg.

### Steps To Reproduce

```markdown
1. Create Collection, insert msg, flush, Drop Collection
2. Restart milvus instances
3. Create collection, insert msg, flush
```

### Anything else?

The root causes is:
1. Datacoord does not detect collection dropped
2. MqttMsgStream `Seek` will consume a msgpack after seek operation

TODO list:
- [x]  Move collection validation before msgstream creation as a workaround #11102 
- [x]  Fix MqttMsgStream seek logic #11171 
- [x]  Allow datacoord know when a collection is dropped
- [ ]  Add unit test to cover the code changes in #11171

**Comment by XuanYang-cn** [comment]
1. DataCoord know nothing about whether a collection is dropped.
 Thus DataCoord makes DataNode to Watch channel of dropped-collection(which will fail for sure)

2. mqMessageStream Seek will wait for the next message and drop it. That's why Seek stucked.
 But the underline reason is unclear

3. DataNode should fail faster before the Seek.

**Comment by XuanYang-cn** [comment]
PR #11102 fixes No.3
