### ISSUE TITLE
[Enhancement]: Separating knowhere from milvus project 

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#11995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The code structure is coupled which has already affected the efficiency of our development.

### Why is this needed?

Benefits:
1. Make engine layer and distributed layer decouple.
2. Run & debug Milvus with a shared library of knowhere.

### Tasks.    
- [x]  Move Knowhere to a new project
- [ ] [Upgrade faiss to 1.7.1 ](https://github.com/milvus-io/milvus/issues/12152)
- [x] Support a brute force search algorithm that is a kind of vector index and doesn't depend on thirdparty libs.
- [x] Support choose one or more vector index to compile

**Comment by xiaofan-luan** [comment]
@XuanYang-cn any ideas?

**Comment by XuanYang-cn** [comment]
Upgrading faiss maybe not be practical for too much effort with too little in return.

**Comment by czs007** [comment]
@jaime0815  can we close this issue ?
