### ISSUE TITLE
[Enhancement]: Support Milvus debug and run on Mac

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#12777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Milvus can be run or compiled on MAC 

### Why is this needed?

 Trying to run/debug is difficult in the MAC/Windows environment.

### Tasks
- [x] [Separating knowhere from milvus project](https://github.com/milvus-io/milvus/issues/11995)
- [x] [Default disable libfiu.](https://github.com/milvus-io/milvus/issues/12151)

### Related
- [Upgrade RocksDB and GoRocksDB](https://github.com/milvus-io/milvus/issues/15489)
