### ISSUE TITLE
[Enhancement]:   Add support for unsigned numeric types.

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#13516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

I would like to add four new  datatype:

DataType_UInt8
DataType_UInt16
DataType_UInt32
DataType_UInt64

- [ ] support for uint8 #13517 
- [ ] support for uint16 #13518
- [ ] support for uint32 #13519 
- [ ] support for uint64 #13520  

### Why is this needed?

Databases like mysql support unsigned integer numbers through keywords such as UNSIGNED.
In order to enrich the data type, we have no reason not to support it.

**Comment by xiaofan-luan** [comment]
leave it since people may need it, mark it as good first issue

**Comment by xiaofan-luan** [comment]
leave it open
