### ISSUE TITLE
[Feature]: Multiple memory replications implementation [QueryNode Part]

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#16291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

https://wiki.lfaidata.foundation/display/MIL/MEP+23+--+Multiple+memory+replication+design

### Task List

- [x]  Add grpc interface for Search & Query #16195
- [x]  Add ShardQueryService Implementation #16470
- [x]  Add ShardCluster implementation #16359 #16470
- [x]  Support search/query part of segments or vchannels #16470 
- [x]  Shard Leader handle hand-off and balance logic

**Comment by congqixia** [comment]
Close as completed
