### ISSUE TITLE
[Feature]: LevelZero Segment

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#27349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Now we need to `inject` when executing compaction, so that new deletion of the compacting segments goes into the correct segment.

`Inject` is used to preventing DN sync streaming data into blob storage. It makes compaction and streaming data coupled, and has introduced many states in compaction execution, has been a huge bug source in DataNode.

We want to remove the `inject` between compaction and sync, decoupling batched data processing with streaming data processing. This could simplify the design of Milvus in many scenarios

1. Compaction are decoupled with streaming data, no need to inject every time.
2. ChannelCP(point saparates streaming data with batched data) can moves freely, no long limited by compaction.
3. Simplify the designment of LogNode. (Or we'll need distributed locks to enable the injection)
...

So the greatest advantage of L0 deletion will be:  **Batch data can only be changed by Compaction**

### Describe the solution you'd like.

# Introducing LevelZero Segment

### glossaries
- `LevelZero`: level of a segment, could be `L0`, `L1`, short for `LevelZero`, `LevelOne`
- `LevelZero Segment`: contains delete data only, also called `LevelZero Delta`, `L0 Delta`, `L0 Deletion`

## Add a LevelZero Segment layer
- Streaming deletions are orgnized as `L0` delete buffer in memory
- `L0` delete buffers are synced into blob storage by size, channel cp advance with LevelZero Segment.
- `L0` compaction transfers multiple `L0` segments into `L1` segment’s deltalogs.
- When performing `L0` compaction, donot allow concurrenct compaction inside a channel.
- Load Segments need to add apply delete data in `L0` segments to all segments

When compaction happens, it doesn’t need to concern about the streaming deletions. And L0 to L1 are controlled by compactions. Hence we can safely remove the injections current in compaction procedure.

![image](https://github.com/milvus-io/milvus/assets/51370125/2c3b2d4e-6f5d-44ad-b14a-3dc40a3fd9d2)

**Comment by XuanYang-cn** [comment]
## Challanges & Solutions

### 1. Handling delegator failover: @congqixia  
1. Load L0 of current target
2. For segments distributed at worker nodes, needs to complete the deltalogs from target, based on a enhancement of loading partial deltalogs @yah01  https://github.com/milvus-io/milvus/pull/26971
3. Go through statslogs before broadcasting L0 deletes, need to **split very large delete msg**

### 2. L0 -> L1 deltalog compaction needs to load ALL sealed segment BF：
There will be ONE statslog for sealed segment，so at most thousands(number of segments) of IO. It's bearable.

### 3. Conditions of L0 compaction
 `L0 ts < min(All growing segments startposition ts)`,  do not couple with growing segments.

### 4. slow inserts/deletes:
Good compaction triggers + seal a segment once an hour, make L0 size in contro

**Comment by XuanYang-cn** [comment]
- [ ] #27350

**Comment by XuanYang-cn** [comment]
# TODOs @yah01 
- [ ] Load&Broadcast L0 delete in delegator

**Comment by yah01** [comment]
> # TODOs @yah01
> * [ ]  Load&Broadcast L0 delete in delegator

Would divide it into 3 tasks:

- [ ] QueryCoord schedules L0 segment first
- [ ] QueryNode skip query/search for L0 segments
- [ ] Shard delegator delivers delete records to the QueryNodes

**Comment by congqixia** [comment]
The latest data flow shall be
![data_flow](https://github.com/milvus-io/milvus/assets/84113973/9a6dffa2-747a-453d-a789-4eeea425559c)

**Comment by XuanYang-cn** [comment]
Related Metrics
![image](https://github.com/milvus-io/milvus/assets/51370125/b0707c0d-3ed2-4ba7-be4f-3a1f9f721b21)

**Comment by XuanYang-cn** [comment]
@yanliang567 It should be in milestone of 2.4.0
