### ISSUE TITLE
[Feature]: L0 Compaction

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus#27606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Enable to do Level0DeleteCompaction

### Describe the solution you'd like.

- [x] Add New Compaction Type #27608
- [x] Change Compaction results proto #28350 
- [x] Do L0 Comaction in DataNode
  - [x] Add deltalog iterators https://github.com/milvus-io/milvus/pull/27643
  - [x] #27436 
  - [x] Add PredictSegments in metacache #28388 
  - [x] Add l0 compaction algo #28470
- [x] Block Other Compactions in DataCoord
  - [x]  Add scheduler https://github.com/milvus-io/milvus/pull/27938
  - [x] Add Views&Trigger https://github.com/milvus-io/milvus/pull/27906
- [x] Add metrics
- [ ] Enable manual compaction triggers l0 compaction

### Anything else? (Additional Context)

See also: #27349 

_No response_

**Comment by XuanYang-cn** [comment]
Done and close it
