### ISSUE TITLE
[Enhancement]: L0 Delta - DataNode support write L0 segment

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#27675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Refactor datanode to support L0 segment sync

- [x] Refine datanode component 
  - [x] Replace all grpc operation with broker
    - [x] Add Broker #27631
    - [x] Replace usage #27676
  - [x] Refine meta cache #27768 #27985
  - [x] Move buffer from `Segment` struct to buffer manager (with delta policy) #27874
  - [x] Refine flush manager #27873
  - [x] Use write node, writeBuffer & sync Manager #28320 
- [ ] Enable Level zero delta policy
  - [x] Sync policy adapts LevelZero segment #28482
- [ ] Metrics
  - [x] datacoord  #28373
  - [ ] datanode
- [ ] Code cleanup, Improvement & fixup logics
  - [x] Comment out code & naming fix #28450
  - [x] Add compacted segment cleanup logic back #28646
  - [x] Output earliest buffer information #28993
  - [x] Separate storage/storagev2 into different abstraction from syncmgr #29413 
  - [ ] Add memory watermark sync policy
  - [x] Fill entry numbers & timestamp range #28858 #28970
  - [x] Allocate logID at most only once for each sync task #29701
- [ ] Bugfix
  - [x] Merged statslog may not generate if flush sync task has no insert data #28494
  - [x] Fix l0 segment deadlock & field missing #28490
  - [x] Fix unstable syncmgr TestCompact unit test #28630 
  - [x] Flush hang & datacoord panic with zero-length compacted result #28628
  - [x] Standalone or datanode panic due to SegmentNotFound error
    - [x] issue #28748 #28736
    - [x] Fix #28755
  - [x] Level zero segments synced as non-flushed state #29569
  - [x] Explicitly pass LevelZero segment ids in vchan info #29612
  - [x] serializer shall bypass L0 segment merge stats step #29636

### Why is this needed?

See also #27349

**Comment by aoiasd** [comment]
> [ ] Add L0 policy

### TODOs
## Datacoord
   - [ ] Support maintain segement info 
   - [ ] Support assign L0 segment
   - [ ] Add new sync policy for L0 segment

**Comment by congqixia** [comment]
The old write flow is
![write_flow_old](https://github.com/milvus-io/milvus/assets/84113973/2f8afdde-04ce-4a25-8245-ded564194b87)
After the refactor of datanode, the component structure and data flow shall be:
![dn_component_refactory](https://github.com/milvus-io/milvus/assets/84113973/16d43e49-c283-4dcb-b23b-14844a94d9af)

**Comment by congqixia** [comment]
With multiple implementation of write buffer, it could be controlled by configuration which delta policy shall datanode use to buffer delta data:
BF Write Buffer
![bf_wb_01](https://github.com/milvus-io/milvus/assets/84113973/5282bf68-2ebf-4696-ad70-16da30db628d)
![bf_wb_02](https://github.com/milvus-io/milvus/assets/84113973/096cf290-0fcb-44e1-8670-d3409831b5f8)
L0 Write Buffer
![l0_wb_01](https://github.com/milvus-io/milvus/assets/84113973/c3e4739c-de4b-44c4-9765-0ca28ff0e765)
![l0_wb_02](https://github.com/milvus-io/milvus/assets/84113973/05c4b50d-e16b-417b-a10c-eb4438c7e6b9)
