### ISSUE TITLE
[Enhancement]: Support 10K level collections/partitions

### ISSUE THREAD

**Issue by wayblink** [milvus-io/milvus#28752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Any optimization to support more collections/partitions/segments.
related issues: #27710 #28343 #24826

Staged goal:
On a 2c 8g instance
Support at least 10K collections with default partitions
Support insert/load 64 collection, each 128 partitions, 768dim HNSW 1 million totally

- [x] Merge flowgraph goroutines into 1 #28654
- [x] Introduce channelCheckpointUpdater to reduce goroutine use in ttNode #28570
- [x] Skip some empty ttMsg in Datanode flowgraph to reduce CPU usage #28756
- [x] Use smaller lock in datacoord.meta.UpdateChannelCheckpoint #28753
