### ISSUE TITLE
[Enhancement]: Management WebUI for enhanced Milvus observability.

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus#36621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Goal
Simplify Milvus operations.

## Value
Enhance system observability for quicker issue resolution.

## Tools Comparison

| Feature                   | Management WebUI                       | Birdwatcher                                      | Attu                                    |
|---------------------------|----------------------------------------|--------------------------------------------------|-----------------------------------------|
| Access        | Web UI                                 | Command-line tool                                | GUI                                     |
| Target User         | Operations/Development                 | Operations                                       | Development                             |
| Integration        | Embedded in Milvus                     | Standalone                                       | Standalone                              |
| Dependency   | Requires healthy Milvus                | Requires healthy Milvus/ETCD                     | Requires healthy Milvus                 |
| Functionality | System environment and runtime metrics | Querying and modifying ETCD metadata, calling some MIlvus APIs | Database management and operations      |

## Demo
Access the local standalone Milvus web UI by address:  http://localhost:9091/webui/

https://github.com/user-attachments/assets/a2ab4f8d-dca2-4b18-a00f-17df3395ac84

## TODO:
- [x]  Basic Web UI Server 

Cluster Metrics
- [x] Display building information.
- [x] Display deployment information.
- [x] Track details of connected clients.

Server Metrics
- [x] Monitor sealed and growing segments on QN and DN.
- [x] Track subscribed channels on QN and DN.
- [ ] Count processed msgpack on QN and DN.
- [x] Server health status.

Database Metrics  
- [x] List all databases (name, creation time).

Collection Metrics  
- [x] Gather basic information (partitions, channels, replicas, index tables).  
- [ ] Monitor row count in collections.  
- [ ] Track read and write operations.  
- [x] List segments.  
- [x] Evaluate the health status of collections.

Replica Metrics
- [x] replica list  
- [ ] Track QPS (Queries Per Second).

Resource group metrics 
- [x]  resource groups list 

Channel Metrics  
- [x] Pchannels list.  
- [ ] Count subscriptions for each Pchannel.  
- [ ] Track producers on each Pchannel.  
- [ ] Monitor timetick, DDL, and DML messages per Pchannel.  
- [ ] List Vchannels for each Pchannel.  
- [x] Capture the latest checkpoint MessageID for each Vchannel.  
- [x] Track the latest ts of the message for each Vchannel.  
- [ ] Monitor messages consumed and produced per second for each Vchannel.  

Task Metrics  
- [x] Track index-building tasks (index name, collection name, index ID, collection ID, type, field).  
- [x] Monitor balance segment tasks (source/dest, segment ID, row count, status).  
- [x] Track balance channel tasks (source/dest, channel name).  
- [x] Monitor flush tasks (collection, partition, segment ID, type, log stats, row count).  
- [x] Track compaction tasks (source/dest segment ID, download/merge time).  
- [x] Monitor load/release tasks for collections, partitions, and segments.  
- [x] Track bulk insert tasks.

DevOps  
- [ ] Update configurations.  
- [x] Collect pprof data for performance profiling.  
- [ ] Enable trace logging for debugging.  
- [x] Visualize memory variables.  
- [ ] Show audit logs of actions taken.  
- [ ] Allow manual execution of flush, compaction, and balance tasks.  
- [ ] Add intelligent diagnosis features.

**Comment by tangkunyin** [comment]
However, I tried http://localhost:9091/webui/ but got 404...

My services under docker container which were running well,I have refered to the [official document](https://milvus.io/docs/milvus-webui.md), but nothing useful things were found

Is there anyone who can tell me how to use webui?

**Comment by xiaofan-luan** [comment]
> However, I tried http://localhost:9091/webui/ but got 404...
> 
> My services under docker container were all running well,I have refered to the [official document](https://milvus.io/docs/milvus-webui.md), but no useful things were found ![image](https://private-user-images.githubusercontent.com/4197468/398848298-8485a61b-f9ea-44d6-85b6-33000cce5293.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NDkwMjksIm5iZiI6MTczNTU0ODcyOSwicGF0aCI6Ii80MTk3NDY4LzM5ODg0ODI5OC04NDg1YTYxYi1mOWVhLTQ0ZDYtODViNi0zMzAwMGNjZTUyOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzBUMDg1MjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmI5ZTE1ZDQ2MGU2OTZjOTYwZDUyOWU0OGM3ZTE5ZGNmYjZjODY2MmViY2U2MWVkZTRkNzZlZDAzOWMyNTg4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.49ttacfNFVAX3znZB4-l9x6-kPJA-PfZ8vhuSxECpYg)
> 
> Is there anyone who can tell me how to use webui? many thanks

1. this is only worked for Milvus 2.5 or above.
2. you will need to expose 9091 port, which already work on your environment.

**Comment by tangkunyin** [comment]
@xiaofan-luan Yes, that's true. It would be better to give a description of the official documentation 🙏🏻
