### ISSUE TITLE
[Enhancement]: Support Search With View Support And Milvus Streaming Service.

### ISSUE THREAD

**Issue by chyezh** [milvus-io/milvus#38125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Parent Issue: #33285

# Design

Also see the parent issue.
Detail coming soon.

# RoadMap

## DataView Implementation

- [ ] DataView Recovery Info Storage.
- [ ] DataView Generation At Segment Meta Layer.
- [ ] Make Sure DataView Generation Works Correctly With Flusher, Import, Compactor, .
- [ ] DataView Work With Garbage Collector.

## QueryView implementation

- [ ] QueryView State Machine At Coord, Streaming, Query.
- [ ] QueryView Sync Up By RPC Between Nodes.
- [ ] QueryView Interface works with Balancer.
- [ ] QueryView Work With Garbage Collector.

## QueryNode Segment Management

- [ ] Segment Lifetime Control
- [ ] Segment Load Scheduler
- [ ] Segment Load Policy At QueryNode
- [ ] Work With StreamingNode Delete Stream

## StreamingNode Delete Stream

- [ ] Delete Stream Client At QueryNode
- [ ] Delete Stream Server At StreamingNode

## Balance At Coord

- [ ] Balance Event Loop At Coord.
- [ ] Balance Strategy.
- [ ] Declaration And Wait Interface At Coord.

## Search With New Architecture

- [ ] Common Utilities For Both Streaming Node And Query Node. #37722,#37531
- [ ] Growing Segment Management At Streaming Node.
- [ ] Search Support At Streaming Node.
- [ ] Search Support At Query Node.
- [ ] 2-Parse-Search At Proxy.

## Streaming Node Rebalance

- [ ] Stateful (R/W) Streaming Node Channel Supported.
- [ ] Multi-Parse-Rebalance At Streaming Node.

## User API 

- [ ] LoadCollection/ReleaseCollection
- [ ] LoadPartition/ReleasePartition

**Comment by chyezh** [comment]
keep it

**Comment by chyezh** [comment]
keep it

**Comment by chyezh** [comment]
see #40451
