### ISSUE TITLE
[Enhancement]: Support Growing Search With Querynode Delegator And Streaming Service

### ISSUE THREAD

**Issue by chyezh** [milvus-io/milvus#38399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Also see the parent issue #33285.
Detail coming soon.

### Why is this needed?

In order to quickly access growing query at streaming architecture in 2.6.
We are now implementing an intermediate version of StreamingService by the current delegator implemetation.
Since 2.6:
- Every Streaming Node will embed a Query Node in it directly (Standalone mode will also embed an extra querynode in it).
- The new query node embedded in streaming node will be different with legacy querynode at coord view by assign a special server label `QUERYNODE_STREAMING-EMBEDED`, named streaming query node, aka. sqn.
- QueryCoord will assign the delegator(channel) only on the sqn, and assign the sealed segment only on legacy querynode.
- The querycoord will assign the channel on the sqn which the vchannel related wal located as much as possible.
- The replica manager will see the sqn, but the resource group manager will not. To avoid break the resource group api.

Here's the TODO list, part of them is extra enhancement for 2.6:

- [x] Make the coord client lazy initialization on streaming node to make streaming node startup fast. #38400
- [x] Make querynode embedded in streamingnode at cluster and standalone mode. #38677
- [x] Change the replica manager to manage the  sqn assignement for replicas, change the balance logic to achieve the channel/segment assignment on sqn/qn respectively. #38677
- [x] Remove the rpc layer when consume wal at same physical node. #38858
- [x] Remove the extra vchannel level wal consumer into wal level. #38516, #38400, #39275
- [x] Enable Kafka for streaming service. #38598
- [x] Enable Rocksmq for streaming service. #38669
- [x] Support Broadcast operation for streaming service. #39007, #39020, #39040, #39522, #39720
- [x] Support write ahead buffer for streaming service to erase the overhead of wal reader. #39771
- [x] Active trigger time tick sync when incoming search and query to speed up strong consistency search. #39799

**Comment by chyezh** [comment]
Done
