### ISSUE TITLE
milvus needs to support compaction 

### ISSUE THREAD

**Issue by sunby** [milvus-io/milvus#9530]
DataCoord will auto flush a segment when it is opened for a long time(eg. 24hours). And users may call flush manually. These cases will cause generation of small segment and it will influence the efficiency of query. We need a compaction mechanism to merge small segments and remove deleted rows to save disk space.

task list:

- [ ] defination of interfaces and data format between datacoord and datanode. #9873 
- [ ] datacoord: trigger logic, plan generation, compaction task handler(success/failure/timeout), segment replacement.
- [ ] datanode: merge logic, concurrency handler, resource management.

task2&3 can be splitted to type1&type2 compaction implementation.

please refer to MEP: https://wiki.lfaidata.foundation/display/MIL/MEP+16+--+Compaction for more details.

**Comment by xiaofan-luan** [comment]
We need a enhancement plan on this since this is a big feature!
I would suggest to divided compaction into stage, single file compaction and multi file compaction

**Comment by sunby** [comment]
> We need a enhancement plan on this since this is a big feature! I would suggest to divided compaction into stage, single file compaction and multi file compaction

I write a MEP and divide it to 2 stages

**Comment by congqixia** [comment]
Flush refactor compaction related:
- [x] Update SegmentInfo proto #9922 
- [x] Modify SaveBinlogPaths to support stats-log and delta-log #10078
- [x] Add flush manager #9985 
- [x] Use single signal to trigger Flush #10057
- [x] Apply new flush logic in data node flowgraph #10141
