### ISSUE TITLE
[Bug]: Etcd ErrCompacted not handle properly

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#9810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When milvus and etcd experiences network problem, the etcd client will try to reconnect with latest successful revision. With auto compaction enabled, the revision may be compacted already. The watch call may block forever or just quit without retry.

### Expected Behavior

Respect watch event err or canceled status and retry if possible

### Steps To Reproduce

```markdown
Running milvus with network issue
```

### Environment

```markdown
- Milvus version: rc7
- Deployment mode(standalone or cluster): cluster
- SDK version(e.g. pymilvus v2.0.0rc2): v2.0.0rc7
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Anything else?

See also #9785

### Task List

- [X] Handle ErrCompacted in WatchDmChannel in DataNode #9788
- [x] Respect err in sessionutil #9811 
- [x] Allow rewatch logic when start watch sessions #12880 
- [ ] Add retry logic for each sessionutil.WatchService call
- [ ] Fix Other watch call
